import React from "react";

import type { Metadata } from 'next'
import { Unbounded } from 'next/font/google'
import './globals.css'

const inter = Unbounded({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio | Luigelo Davila',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
